[versions]
simplified-annotations = "2.6.0"
annotations = "26.0.2"
log4j2 = "2.25.3"
snakeyaml = "2.0"

[libraries]
simplified-annotations = { group = "io.github.simplified-dev", name = "annotations", version.ref = "simplified-annotations" }
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }
log4j2-api = { group = "org.apache.logging.log4j", name = "log4j-api", version.ref = "log4j2" }
snakeyaml = { group = "org.yaml", name = "snakeyaml", version.ref = "snakeyaml" }
